-- ============================================================
-- MICHAELIN MAP — SEED DATA
-- Run AFTER 2026-08-05-supabase-schema.sql
-- ============================================================

-- ---------- TAG VOCABULARIES (93 tags) ----------
insert into tags (facet, label, slug, is_derived, sort_order) values
  ('cuisine', 'BBQ', 'bbq', false, 0),
  ('cuisine', 'Tex-Mex', 'tex-mex', false, 1),
  ('cuisine', 'Tacos', 'tacos', false, 2),
  ('cuisine', 'Interior Mexican', 'interior-mexican', false, 3),
  ('cuisine', 'Southern & Comfort', 'southern-comfort', false, 4),
  ('cuisine', 'Burgers', 'burgers', false, 5),
  ('cuisine', 'Pizza', 'pizza', false, 6),
  ('cuisine', 'Italian', 'italian', false, 7),
  ('cuisine', 'Steakhouse', 'steakhouse', false, 8),
  ('cuisine', 'Seafood', 'seafood', false, 9),
  ('cuisine', 'New American', 'new-american', false, 10),
  ('cuisine', 'Japanese', 'japanese', false, 11),
  ('cuisine', 'Sushi', 'sushi', false, 12),
  ('cuisine', 'Ramen', 'ramen', false, 13),
  ('cuisine', 'Korean', 'korean', false, 14),
  ('cuisine', 'Chinese', 'chinese', false, 15),
  ('cuisine', 'Thai', 'thai', false, 16),
  ('cuisine', 'Vietnamese', 'vietnamese', false, 17),
  ('cuisine', 'Indian', 'indian', false, 18),
  ('cuisine', 'Middle Eastern', 'middle-eastern', false, 19),
  ('cuisine', 'Mediterranean', 'mediterranean', false, 20),
  ('cuisine', 'Ethiopian', 'ethiopian', false, 21),
  ('cuisine', 'Caribbean', 'caribbean', false, 22),
  ('cuisine', 'Vegetarian-forward', 'vegetarian-forward', false, 23),
  ('cuisine', 'Breakfast & Diner', 'breakfast-diner', false, 24),
  ('cuisine', 'Bakery & Pastry', 'bakery-pastry', false, 25),
  ('cuisine', 'Coffee', 'coffee', false, 26),
  ('cuisine', 'Cocktails & Bar Food', 'cocktails-bar-food', false, 27),
  ('cuisine', 'British', 'british', false, 28),
  ('cuisine', 'French', 'french', false, 29),
  ('cuisine', 'Spanish', 'spanish', false, 30),
  ('cuisine', 'Portuguese', 'portuguese', false, 31),
  ('cuisine', 'Greek', 'greek', false, 32),
  ('cuisine', 'Turkish', 'turkish', false, 33),
  ('cuisine', 'Brazilian', 'brazilian', false, 34),
  ('cuisine', 'Peruvian', 'peruvian', false, 35),
  ('cuisine', 'Modern European', 'modern-european', false, 36),
  ('format', 'Sit-down restaurant', 'sit-down-restaurant', false, 0),
  ('format', 'Food truck', 'food-truck', false, 1),
  ('format', 'Counter service', 'counter-service', false, 2),
  ('format', 'Bar with real food', 'bar-with-real-food', false, 3),
  ('format', 'Café & bakery', 'caf-bakery', false, 4),
  ('format', 'Fine dining', 'fine-dining', false, 5),
  ('format', 'Trailer park / multi-vendor', 'trailer-park-multi-vendor', false, 6),
  ('occasion', 'First date', 'first-date', false, 0),
  ('occasion', 'Impress a client', 'impress-a-client', false, 1),
  ('occasion', 'Bring your parents', 'bring-your-parents', false, 2),
  ('occasion', 'Big group, 8 or more', 'big-group-8-or-more', false, 3),
  ('occasion', 'Solo with a book', 'solo-with-a-book', false, 4),
  ('occasion', 'Kids in tow', 'kids-in-tow', false, 5),
  ('occasion', 'Out-of-towner starter pack', 'out-of-towner-starter-pack', false, 6),
  ('occasion', 'Late night', 'late-night', false, 7),
  ('occasion', 'Before a show', 'before-a-show', false, 8),
  ('occasion', 'Long lunch', 'long-lunch', false, 9),
  ('occasion', 'Celebration', 'celebration', false, 10),
  ('occasion', 'Cheap and fast', 'cheap-and-fast', false, 11),
  ('occasion', 'Night out', 'night-out', false, 12),
  ('occasion', 'Vacation', 'vacation', false, 13),
  ('vibe', 'Loud', 'loud', false, 0),
  ('vibe', 'Quiet enough to talk', 'quiet-enough-to-talk', false, 1),
  ('vibe', 'Patio', 'patio', false, 2),
  ('vibe', 'Rooftop', 'rooftop', false, 3),
  ('vibe', 'Dog-friendly', 'dog-friendly', false, 4),
  ('vibe', 'Dark and moody', 'dark-and-moody', false, 5),
  ('vibe', 'Bright and airy', 'bright-and-airy', false, 6),
  ('vibe', 'Counter seating', 'counter-seating', false, 7),
  ('vibe', 'Live music', 'live-music', false, 8),
  ('vibe', 'Game on the TV', 'game-on-the-tv', false, 9),
  ('vibe', 'Air conditioning that actually works', 'air-conditioning-that-actually-works', false, 10),
  ('logistics', 'Open late', 'open-late', true, 0),
  ('logistics', 'Open Monday', 'open-monday', true, 1),
  ('logistics', 'Closes early', 'closes-early', true, 2),
  ('logistics', 'Open for breakfast', 'open-for-breakfast', true, 3),
  ('logistics', 'Walk-in only', 'walk-in-only', false, 0),
  ('logistics', 'Reservations essential', 'reservations-essential', false, 1),
  ('logistics', 'Reservations weeks out', 'reservations-weeks-out', false, 2),
  ('logistics', 'Cash only', 'cash-only', false, 3),
  ('logistics', 'Parking is a problem', 'parking-is-a-problem', false, 4),
  ('logistics', 'The line is real', 'the-line-is-real', false, 5),
  ('logistics', 'Order at the counter', 'order-at-the-counter', false, 6),
  ('dietary', 'Vegetarian options', 'vegetarian-options', false, 0),
  ('dietary', 'Vegan options', 'vegan-options', false, 1),
  ('dietary', 'Gluten-free options', 'gluten-free-options', false, 2),
  ('dietary', 'Genuinely good for vegetarians', 'genuinely-good-for-vegetarians', false, 3),
  ('character', 'Hangover triage', 'hangover-triage', false, 0),
  ('character', '3am bad decision', '3am-bad-decision', false, 1),
  ('character', 'Your vegan friend won''t complain', 'your-vegan-friend-won-t-complain', false, 2),
  ('character', 'Tourist bait, but actually good', 'tourist-bait-but-actually-good', false, 3),
  ('character', 'Where to break up with someone', 'where-to-break-up-with-someone', false, 4),
  ('character', 'Trying to impress, but not that hard', 'trying-to-impress-but-not-that-hard', false, 5),
  ('character', 'Worth the charging detour', 'worth-the-charging-detour', false, 6),
  ('character', 'Order the weird thing', 'order-the-weird-thing', false, 7),
  ('character', 'Somehow always empty and always good', 'somehow-always-empty-and-always-good', false, 8);

-- ---------- FIELD REPORT QUESTIONS (38 questions) ----------
insert into questions (prompt, input_type, unit_label, options, slider_labels, judgment_prompt, requires_review) values
  ('Temperature of the food on arrival', 'number', '°F', null::jsonb, null::jsonb, null, false),
  ('Ambient temperature of the room. Best guess. No phones.', 'number', '°F', null::jsonb, null::jsonb, null, false),
  ('Seconds between sitting down and first contact with a human', 'number', 'seconds', null::jsonb, null::jsonb, null, false),
  ('Ice cubes in your drink', 'number', 'cubes', null::jsonb, null::jsonb, null, false),
  ('Minutes elapsed before you knew what you wanted', 'number', 'minutes', null::jsonb, null::jsonb, null, false),
  ('Distance from the establishment to the nearest body of water', 'number', 'feet', null::jsonb, null::jsonb, null, false),
  ('Ceiling height, measured in hands', 'number', 'hands', null::jsonb, null::jsonb, null, false),
  ('Steps from the front door to your seat', 'number', 'steps', null::jsonb, null::jsonb, null, false),
  ('Distance from your table to the nearest other table, in forearms', 'number', 'forearms', null::jsonb, null::jsonb, null, false),
  ('Walking minutes from where you parked', 'number', 'minutes', null::jsonb, null::jsonb, null, false),
  ('Was the front door heavier than you anticipated?', 'yes_no', null, null::jsonb, null::jsonb, null, false),
  ('How far was the bathroom?', 'compound', 'steps', null::jsonb, null::jsonb, 'Was it worth it?', false),
  ('Colour of your chair', 'color', null, null::jsonb, null::jsonb, 'Is that good or bad?', false),
  ('Dominant wall colour', 'color', null, null::jsonb, null::jsonb, null, false),
  ('Colour of the napkin', 'color', null, null::jsonb, null::jsonb, null, false),
  ('Colour of the most prominent sauce', 'color', null, null::jsonb, null::jsonb, null, false),
  ('Was there a colour present that you would describe as unearned?', 'yes_no', null, null::jsonb, null::jsonb, null, false),
  ('Patrons observed wearing hats', 'number', 'hats', null::jsonb, null::jsonb, null, false),
  ('Dogs visible from your seat', 'number', 'dogs', null::jsonb, null::jsonb, null, false),
  ('Televisions', 'number', 'TVs', null::jsonb, null::jsonb, null, false),
  ('Plant status', 'single_choice', null, '["Alive","Plastic","Both","None detected"]'::jsonb, null::jsonb, null, false),
  ('Tables you assessed to be on a first date', 'number', 'tables', null::jsonb, null::jsonb, null, false),
  ('Ceiling fans', 'compound', 'fans', null::jsonb, null::jsonb, 'Were they operating in the correct direction?', false),
  ('Napkins used', 'compound', 'napkins', null::jsonb, null::jsonb, 'Was this the correct number?', false),
  ('Chair comfort', 'slider', null, null::jsonb, '["Actively hostile","I fell asleep"]'::jsonb, null, false),
  ('Lighting', 'slider', null, null::jsonb, '["Surgical","Could not read the menu"]'::jsonb, null, false),
  ('Commitment to the theme', 'slider', null, null::jsonb, '["No theme detected","Total, unbroken"]'::jsonb, null, false),
  ('The bread situation', 'slider', null, null::jsonb, '["No bread","Bread overwhelmed the meal"]'::jsonb, null, false),
  ('Volume', 'slider', null, null::jsonb, '["Library","Had to point at the menu"]'::jsonb, null, false),
  ('Did anyone sing Happy Birthday?', 'yes_no', null, null::jsonb, null::jsonb, null, false),
  ('Did water arrive without you asking?', 'yes_no', null, null::jsonb, null::jsonb, null, false),
  ('Were there crayons?', 'yes_no', null, null::jsonb, null::jsonb, null, false),
  ('Did you have to ask what something on the menu was?', 'yes_no', null, null::jsonb, null::jsonb, null, false),
  ('Was there a mirror positioned such that you accidentally watched yourself eat?', 'yes_no', null, null::jsonb, null::jsonb, null, false),
  ('Last song you heard playing', 'text_short', null, null::jsonb, null::jsonb, null, true),
  ('One object present that should not have been', 'text_short', null, null::jsonb, null::jsonb, null, true),
  ('What the person nearest you ordered', 'text_short', null, null::jsonb, null::jsonb, null, true),
  ('The dish you would order again', 'text_short', null, null::jsonb, null::jsonb, null, true);

-- ---------- EXAMPLE CODE ----------
insert into codes (code, label, message, theme, active) values
  ('DEMO', 'Example code — delete or edit in admin',
   'You found it.',
   '{"primary":"#F5C518","mapStyle":"amber"}'::jsonb, true);
